package nl.part66l.logbook.pdf

import android.content.Context
import com.tom_roush.pdfbox.pdmodel.PDDocument
import com.tom_roush.pdfbox.pdmodel.PDPageContentStream
import com.tom_roush.pdfbox.pdmodel.font.PDFont
import com.tom_roush.pdfbox.pdmodel.graphics.color.PDDeviceRGB
import com.tom_roush.pdfbox.pdmodel.graphics.image.PDImageXObject
import com.tom_roush.pdfbox.pdmodel.graphics.state.PDExtendedGraphicsState
import nl.part66l.logbook.R

/**
 * The branding every generated PDF shares: a large, faint centred watermark, and a footer
 * line naming the app. Kept separate from [CrsPdfRenderer] and [SigningInfoPdfRenderer] so
 * both draw identical branding instead of two hand-tuned copies drifting apart.
 *
 * An earlier version put the logo in a blue header band — dropped: at a size small enough to
 * fit a header strip it read as barely visible, and the band ate real content space on every
 * page. A large, faint watermark behind the content reads as branding without costing layout
 * room, since [PageWriter][com.tom_roush.pdfbox.pdmodel.PDPageContentStream] draws it before
 * anything else — real content always paints over it, never the other way round.
 */
object PdfBranding {
    const val MM = 72f / 25.4f
    const val FOOTER_TEXT = "This file is generated by AMLog for Android."

    private val FOOTER_GREY = floatArrayOf(0.55f, 0.55f, 0.55f)
    private const val WATERMARK_WIDTH_FRACTION = 0.65f
    private const val WATERMARK_ALPHA = 0.05f

    /**
     * The alpha-only themed-icon layer, not the white-on-transparent adaptive foreground —
     * that layer's ink is white, which is invisible against white paper at any opacity. This
     * one's ink is opaque black, which reads as a faint grey silhouette instead.
     */
    fun loadWatermark(document: PDDocument, context: Context): PDImageXObject {
        val bytes = context.resources.openRawResource(R.mipmap.ic_launcher_monochrome).use { it.readBytes() }
        return PDImageXObject.createFromByteArray(document, bytes, "amlog-watermark")
    }

    /** Draws [watermark] large and centred on the page, faint enough that any content painted afterwards stays fully legible. */
    fun drawWatermark(stream: PDPageContentStream, pageWidth: Float, pageHeight: Float, watermark: PDImageXObject) {
        val size = pageWidth * WATERMARK_WIDTH_FRACTION
        val x = (pageWidth - size) / 2f
        val y = (pageHeight - size) / 2f
        val transparency = PDExtendedGraphicsState().apply { setNonStrokingAlphaConstant(WATERMARK_ALPHA) }
        stream.saveGraphicsState()
        stream.setGraphicsStateParameters(transparency)
        stream.drawImage(watermark, x, y, size, size)
        stream.restoreGraphicsState()
    }

    /**
     * [FOOTER_TEXT], centred at [y] — left to the caller to place, since [CrsPdfRenderer] folds
     * it into the same line as its existing document-number/page-count footer, while
     * [SigningInfoPdfRenderer] (no page count, nothing else on that line) uses it standalone.
     */
    fun drawFooterText(stream: PDPageContentStream, pageWidth: Float, y: Float, font: PDFont, size: Float = 6.5f, color: FloatArray = FOOTER_GREY) {
        val width = font.getStringWidth(FOOTER_TEXT) / 1000f * size
        stream.setNonStrokingColorSpace(PDDeviceRGB.INSTANCE)
        stream.setNonStrokingColor(color)
        stream.beginText()
        stream.setFont(font, size)
        stream.newLineAtOffset((pageWidth - width) / 2f, y)
        stream.showText(FOOTER_TEXT)
        stream.endText()
    }
}
